development:
  adapter: postgresql
  encoding: unicode
  database: pep-campaigns_development

test:
  adapter: postgresql
  encoding: unicode
  database: pep-campaigns_test

production:
  adapter: postgresql
  encoding: unicode
  database: pep-campaigns_production
